export const Config = {
  MAX_NOTES_LENGTH: 500,
  MAX_TAGS_PER_PLANT: 10,
  MAX_IMAGE_SIZE_BYTES: 2 * 1024 * 1024,
  MAX_STORAGE_SIZE_BYTES: 5 * 1024 * 1024,
  AI_CONFIDENCE_THRESHOLD: 0.6,
  AI_MIN_CONFIDENCE: 0.3,
  RATE_LIMIT_CALLS_PER_HOUR: 5,
  OTP_RESEND_COOLDOWN_SECONDS: 60,
  MAX_OTP_ATTEMPTS: 5,
  DATA_DELETION_DAYS: 30,
  LOCAL_FUNCTION_URL: process.env.EXPO_PUBLIC_LOCAL_FUNCTION_URL,
} as const;
